name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew
      - name: Build Project
        run: ./gradlew build
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t jorgemaceulevicius94/laundry-app:latest .
      - name: Publish image to docker hub
        run: docker push jorgemaceulevicius94/laundry-app:latest
#
#  deploy:
#    needs: build
#    runs-on: [aws-ec2]
#    steps:
#      - name: Pull image from docker hub
#        run: docker pull danieleleaoe/deploy_ghactions:latest
#      - name: Remove docker container
#        run: docker rm -f deploy_ghactions
#      - name: Run docker container
#        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} --name deploy_ghactions danieleleaoe/deploy_ghactions